version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 18
  pre_build:
    commands:
      - npm ci --legacy-peer-deps
  build:
    commands:
      - CI=false npm run build
  post_build:
    commands:
      - aws s3 sync dist/ s3://onboarding.dglide.com --delete
      - aws cloudfront create-invalidation --distribution-id E1WSQJ05NNIEGO --paths "/*"
